name: "Main workflow"
on: [pull_request, push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node_version: 14.x
            - name: Install dependencies
              run: yarn
            - name: Check for linting errors
              run: yarn lint:check
